@startuml
!define LC() bold,#770077
!define MC() #bb0000

left to right direction

'skinparam linetype ortho
skinparam linetype line

(*) --> "앱 기동"

"앱 기동" --> "메인"
"앱 기동" -r-> " *은 로그인 한정 기능"
-[MC()]r-> "메인 기능"
-[LC()]r-> "상품 페이지"

' ☆ 지역 설정

"메인" -[MC()]-> "지역 설정"
"지역 설정" --> "지역 기반 주변 매장 검색"
"지역 설정" --> "지역 기반 마감 임박 상품 검색"
"지역 기반 마감 임박 상품 검색" -[hidden]left-> "지역 기반 주변 매장 검색"
"지역 기반 주변 매장 검색" --> "매장"
"지역 기반 마감 임박 상품 검색" -[LC()]-> "상품"

"지역 설정" -[hidden]right-> "검색"

' ☆ 검색

"메인" -[MC()]-> "검색"

"검색" --> "검색어 기반 매장 검색"
"검색" --> "검색어 기반 상품 검색"

"검색어 기반 매장 검색" -[hidden]left-> "검색어 기반 상품 검색"

"검색어 기반 매장 검색" ---> "매장"
"검색어 기반 상품 검색" --[LC()]-> "상품"

' ☆ 지도

"메인" -[MC()]-> "근처 매장 조회"
--> "카카오 맵"
--> "주위 매장 마커 검색"
--> "매장"

' ☆ 구매 내역

"메인" -[MC()]r-> "구매 내역*"
"구매 내역*" -r-> "구매 내역 조회*"

' ☆ 카테고리

"메인" -[MC()]--> "카테고리"
"카테고리" --> "카테고리 기반 매장 검색"
"카테고리 기반 매장 검색" --> "매장"

' ☆ 찜 목록

"메인" -[MC()]-> "찜 목록*"
"지역 설정" -[hidden]right-> "찜 목록*"

"찜 목록*" --> "찜한 매장 조회*"
"찜 목록*" --> "찜한 상품 조회*"
"찜한 매장 조회*" -[hidden]left-> "찜한 상품 조회*"

"찜한 매장 조회*" --> "매장"
"찜한 상품 조회*" -[LC()]-> "상품"

' ☆ 마이페이지

"메인" -[MC()]l-> "내 정보"

"내 정보" -l-> "로그인 페이지"
"로그인 페이지" -d-> "로그인"
"로그인 페이지" -d-> "소셜 로그인"
"로그인 페이지" -d-> "회원가입"

"고객센터" -[hidden]left-> "로그아웃"
"로그아웃" -[hidden]left-> "로그인 페이지"
"내 정보" -u-> "로그아웃"
"내 정보" -u-> "고객센터"

' -----
"매장" -[LC()]-> "상품"
"상품" --r--> "결제"
"결제" -r-> "구매 내역*"
' -----



@enduml