@startuml

(*) --> "사이트 대문"
--> "회원가입"
-l-> "로그인"
"사이트 대문" --> "로그인"
"로그인"  --> "SALEND"

"SALEND" --> "상품 등록"
"SALEND" --> "상품 관리"
"SALEND" --> "매장 설정"

"상품 등록" -r-> "상품 관리"

"상품 관리" --> "상품 정보 수정"
"상품 관리" --> "상품 상태 변경"

"매장 설정" -r-> "매장 정보 변경"
"매장 설정" --> "매장 인증"
-r-> "서버 검증"
"서버 검증" -l-> "매장 인증"

@enduml